site_name: ryxpress-docs
site_description: Documentation for ryxpress
repo_url: https://github.com/b-rodrigues/ryxpress
nav:
  - Home: index.md
  - API:
      - Reference: reference.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - git-revision-date-localized:
      enabled: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/b-rodrigues/ryxpackage
